enum ApiErrorCode {
  UNKNOWN_ERROR = 0,
  RECORD_NOT_FOUND = 1001,
  CHAT_ROOM_RECORD_NOT_FOUND = 1002,
  CHAT_ROOM_RECORD_NOT_FOUND_SEARCH_MESSAGE = 1003,

  RECORD_FETCH_FAILED = 2001,
  CHAT_ROOM_RECORD_FETCH_FAILED = 2002,
  CHAT_ROOM_RECORD_FETCH_FROM_DB_FAILED = 2003,
  CHAT_ROOM_RECORD_FETCH_FROM_SERVICE_FAILED = 2004,

  INVALID_URL_PARAM = 3001,
}

export { ApiErrorCode };
